server:
  port: 8088

spring:
  application:
    name: recurring-transaction-service
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://admin-server:8082}
        instance:
          service-base-url: http://spendsmart-recurring:8088/api
          management-base-url: http://spendsmart-recurring:8088/api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/recurring_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:4f2b1a8d9e7c3f6a5b4c9e8d7f6a5b4c3e2d1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8}

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
    instances:
      notification-service:
        baseConfig: default
      income-service:
        baseConfig: default
      expense-service:
        baseConfig: default
